spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456Qwe

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0

qiniu:
  accessKey: ygdIFwQ3td8D5occ_MXOBp8ToO5HuNYnubaZYsEk
  secretKey: 5F21zs3od_C_w8oSB8gYW1vehwVO_4IP9JDYoRbC
  buckName: community-manage
  qiniuDomin: qp859jol4.hn-bkt.clouddn.com





